name: Main
on: push

jobs:
  test-and-release:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Type-check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage

      - name: Format-check
        run: npm run format -- --check

      - name: Build
        run: npm run build

      - name: Coverage
        uses: codecov/codecov-action@v3
